### ISSUE TITLE
#digMit18 GitHub Usernames

### ISSUE THREAD

**Issue by RJP43** [DigitalMitford/DigMitCS#15]
Please add your GitHub usernames below!!!!

**Comment by MDMoll** [comment]
@MDMoll was here

**Comment by alcoldwell** [comment]
alcoldwell

**Comment by RJP43** [comment]
Here are some of the Git resources shared in our Potluck session:
https://learngitbranching.js.org/
http://rogerdudler.github.io/git-guide/

**Comment by BeggarsOperaDH** [comment]
BeggarsOperaDH

**Comment by hawc2** [comment]
hawc2

**Comment by KellieDC** [comment]
KellieDC

Kellie Donovan-Condron

**Comment by DLCalhoun** [comment]
DLCalhoun

**Comment by RJP43** [comment]
@alcoldwell Here is the quick reference git command cheat sheet - https://github.com/ebeshero/DHClass-Hub/blob/master/Git_BasicCommands.md
