### ISSUE TITLE
Rides To and From Oakland for Thursday 

### ISSUE THREAD

**Issue by RJP43** [DigitalMitford/DigMitCS#17]
**Steve's Van** (6 seats):  
Steve (@BeggarsOperaDH)  
Mark (@MDMoll)  
Alex (@hawc2)  
Anne  
Andrea (@alcoldwell)  
Becca  
  
**Greg's Car** (5 seats):   
Greg  
Elisa (@ebeshero)  
Ally (@quantum-satire)  
Allison  
Sara  
  
**Amy's Car** (4 seats - not returning to Greensburg):  
Amy  
Mariah  
Juliet  
  
**Sam's Car** (4 seats):   
Sam  
Kellie (@KellieDC)  
Lisa  
Renee  
  
Becca will drive if there is overflow. Jon (@jonhoranic) do you need a ride to and from? 
Elisa will likely be in Amy's car on the way there but will come back with Greg.

**Comment by KellieDC** [comment]
What time are we gathering to head up there?

K

**Comment by ebeshero** [comment]
@KellieDC Probably around 8am.
