### ISSUE TITLE
Project Mgmt Workshop

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DigMitCS#4]
@abrennr I've been consulting with Mike and Patrick for their parts of the workshop (schedule here: https://ebeshero.github.io/DigMitCS/ ), but I haven't yet checked in with you... Would you like to consult a little? I'm around in Pittsburgh tomorrow and could meet you and/or @mbolam sometime I think after noon.

**Comment by abrennr** [comment]
@ebeshero -- sure, that would be great. Unfortunately the only time that looks good for me tomorrow is 4-5pm. Any chance that would work for you?

**Comment by ebeshero** [comment]
@abrennr Sure—I am free then! Where should we meet?

**Comment by abrennr** [comment]
@ebeshero let's meet in the digital scholarship commons area.

**Comment by ebeshero** [comment]
@abrennr See you then and there. Thanks!

**Comment by ebeshero** [comment]
@abrennr will guide our team through a project planning exercise for about 20 mins, and then group the other participants up to talk about their projects. 

* Try out some project management tools 
* navigating institutional politics
* multitasking and project dev--keeping 
* steps to ensure sustainability
* bus factor
